# How to complete this assignment
First, download [this Kaggle dataset](https://www.kaggle.com/hugomathien/soccer) and extract *sqlite* database. You may need to register at https://www.kaggle.com/ beforehand. Then complete 15 graded tasks below, the score is given in brackets. Finally submit the resulting `.ipynb` file to rs-app Auto-test.

- Do not delete or rename the variables given before the inscription `#your code here`, they are needed for the correct verification.
- Do not change the code in the last Notebook cell, it is required for the server check.
- Your Notebook must run completely without errors to be graded! Please check everything before submission by going *Cell -> Run All*

## Some important notes
- If you need to **calculate the number of "something"** that means we expect you to assign an Integer to the given variable
- If you need to **make a list of "something"** we expect you to assign a Python list with appropriate values to the given variable
- If you need to find a **specifi—Å player, day of the week, team, etc.** we expect you to assign a String with the full name of the entity to the given variable (`player_name`, day of week full name, `team_name`, etc.)

In [1]:
import sqlite3
import pandas as pd
import os
import sys

pd.set_option('display.max_column', None)

In [2]:
# Leave that code unchanged, it is required for the server check!
db = sqlite3.connect(os.environ.get("DB_PATH") or 'database.sqlite')

In [3]:
# You may load the data from SQL table directly to the Pandas dataframe as
player_data = pd.read_sql("SELECT * FROM Player;", db)

In [4]:
player_data.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

**Task 1 (0.25 point).** Calculate the number of players with a height between 180 and 190 inclusive

In [5]:
players_180_190 = len(player_data.height.loc[(player_data.height >=180) & (player_data.height <= 190)])

In [6]:
assert(isinstance(players_180_190, int))

**Task 2 (0.25 point).** Calculate the number of players born in 1980. <br>
**Hint:** you may want to cast your 'birthday' column to DateTime type by [pandas.to_datetime](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html)

In [7]:
player_data.birthday = pd.to_datetime(player_data.birthday)

players_1980 = len(player_data.birthday[player_data.birthday.dt.year == 1980])

In [8]:
assert(isinstance(players_1980, int))

**Task 3 (0.25 point).** Make a list of the top 10 players with the highest weight sorted in descending order. If there are several players with the same weight put them in the lexicographic order by name.

In [9]:
highest_players = player_data.sort_values(by=["weight", "player_name"], ascending=[False, True]).iloc[0:10, 2].to_list()

In [10]:
highest_players

['Kristof van Hout',
 'Tim Wiese',
 'Jeroen Verhoeven',
 'Ishmael Miller',
 'Cassio',
 'Christopher Samba',
 'Lars Unnerstall',
 'Marcus Hahnemann',
 'Abdoulaye Faye',
 'Enoch Showunmi']

In [11]:
assert(len(highest_players) == 10)
assert(isinstance(highest_players, list))
for i in range(10):
    assert(isinstance(highest_players[i], str))

**Task 4 (0.5 point).** Make a list of tuples containing years along with the number of players born in that year from 1980 up to 1990. <br>
**Structure example**: [(1980, 123), (1981, 140) ..., (1990, 83)] -> There were born 123 players in 1980, there were born 140 players in 1981 and etc.

In [12]:
player_data[player_data.birthday.dt.year == 1980].count()[0]

434

In [13]:
#years_born_players = # Your code here
years_born_players = []
for i in range(1980,1991):
    cont = int(player_data[player_data.birthday.dt.year == i].count()[0])
    years_born_players.append((i,cont))

In [14]:
assert(len(years_born_players) == 11)
assert(isinstance(years_born_players, list))
for i in range(10):
    assert(isinstance(years_born_players[i], tuple))
    assert(isinstance(years_born_players[i][0], int))
    assert(isinstance(years_born_players[i][1], int))

In [15]:
years_born_players

[(1980, 434),
 (1981, 475),
 (1982, 487),
 (1983, 541),
 (1984, 607),
 (1985, 593),
 (1986, 710),
 (1987, 722),
 (1988, 802),
 (1989, 723),
 (1990, 696)]

**Task 5 (0.5 point).** Calculate the mean and the standard deviation of the players' **height** with the name **Adriano**. <br>
**Note:** Name is represented by the first part of `player_name`.

In [16]:
a_m = player_data.loc[player_data.player_name.str.startswith('Adriano')]
adriano_mean, adriano_std = a_m.height.mean(), a_m.height.std()

In [17]:
a_m

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
184,185,167648,Adriano De Pierro,193351,1991-01-11,185.42,170
185,186,280969,Adriano Facchini,205122,1983-03-12,187.96,172
186,187,39190,Adriano Ferreira Pinto,163653,1979-12-10,177.80,179
187,188,172172,Adriano Jose de Lara,193874,1987-12-09,185.42,190
188,189,39199,Adriano Pereira da Silva,135530,1982-04-03,180.34,165
189,190,38122,Adriano Russo,137419,1987-06-06,185.42,159
190,191,121923,Adriano,183243,1982-01-21,175.26,168
191,192,30690,Adriano,106019,1982-02-17,187.96,194
192,193,33992,Adriano,164082,1984-10-26,172.72,161
193,194,41109,Adriano,152769,1980-01-29,182.88,176

In [18]:
adriano_mean

182.118

In [19]:
assert(isinstance(adriano_mean, float))
assert(isinstance(adriano_std, float))

**Task 6 (0.75 point).** How many players were born on each day of the week? Find the day of the week with the minimum number of players born.

In [20]:
player_data.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08,182.88,154

In [21]:
counter =[]
for i in range(7):
        counter.append((player_data.birthday.dt.dayofweek == i).sum())
counter

[1643, 1652, 1607, 1648, 1685, 1463, 1362]

In [22]:
(player_data.birthday.dt.day_name() == 'Sunday').sum()

1362

In [23]:
dow_with_min_players_born = 'Sunday'

In [24]:
assert(isinstance(dow_with_min_players_born, str))

**Task 7 (0.75 point).** Find a league with the most matches in total. If there are several leagues with the same amount of matches, take the first in the lexical order.

In [25]:
league_data = pd.read_sql("SELECT * FROM League", db)
match_data = pd.read_sql("SELECT * FROM Match", db)

match = match_data.set_index('country_id')
league = league_data.set_index('country_id')
new = match.join(league, lsuffix='_m', rsuffix='_l').reset_index()
alo = new['name'].value_counts()[0]


league_most_matches = 'England Premier League'

In [26]:
assert(isinstance(league_most_matches, str))

**Task 8 (1.25 point).** Find a player who participated in the largest number of matches during the whole match history. Assign a `player_name` to the given variable

In [27]:
dfs = []
df = match_data.loc[:,'home_player_1': 'away_player_11']
for col in df.columns:
    top_values = []
    top_values = df[col].mode()
    dfs.append(pd.DataFrame({col: top_values}).reset_index(drop=True))
pd.concat(dfs, axis=1)


aaa = [31293.0, 33025.0, 35606.0, 30627.0, 24846.0, 39854.0, 154257.0, 30955.0,36378.0,107417.0,27734.0,31293.0,33988.0,35606.0,30627.0,24846.0,39854.0,154257.0,75192.0,36378.0,35724.0,33028.0]
o = []
for a in aaa:
    o.append((match_data.loc[:,'home_player_1': 'away_player_11'] ==  a).sum().sum())
    
    
(match_data.loc[:,'home_player_1': 'away_player_11'] ==  31293.0).sum().sum()

player_data.loc[player_data.player_api_id == 31293.0]

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
9993,10009,31293,Steve Mandanda,163705,1985-03-28,185.42,181

In [28]:
max_matches_player = 'Steve Mandanda'

In [29]:
assert(isinstance(max_matches_player, str))

**Task 9 (1.5 point).** List top-5 tuples of most correlated **player's characteristics** in the descending order of the absolute [Pearson's coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient) value.

**Note 1:** Players characteristics are all the columns in `Player_Attributes` table except `[id, player_fifa_api_id, player_api_id, date, preferred_foot, attacking_work_rate, defensive_work_rate]`). <br>
**Note 2:** Exclude duplicated pairs from the list. E.g. ('gk_handling', 'gk_reflexes') and ('gk_reflexes', 'gk_handling') are duplicates, leave just one of them in the resulting list.

**Hint:** You may use [dataframe.corr()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html) for calculating pairwise Pearson correlation.

In [30]:
player_attr = pd.read_sql("SELECT * FROM Player_Attributes", db)
player_attr.drop([], axis='columns', inplace=True)

In [31]:
player_attr.corr().abs().unstack().sort_values(ascending=False).drop_duplicates()[:10]

id               id                 1.000000
gk_reflexes      gk_positioning     0.966711
                 gk_handling        0.966326
gk_positioning   gk_handling        0.966301
standing_tackle  sliding_tackle     0.953104
marking          standing_tackle    0.950134
                 sliding_tackle     0.937534
gk_diving        gk_reflexes        0.935209
                 gk_positioning     0.926366
                 gk_handling        0.925160
dtype: float64

In [32]:
top_correlated_features = [('gk_reflexes','gk_positioning'),('gk_reflexes','gk_handling'),('gk_handling','gk_positioning'),('sliding_tackle','standing_tackle'),('standing_tackle','marking')]

In [33]:
assert(len(top_correlated_features) == 5)
assert(isinstance(top_correlated_features, list))
for i in range(5):
    assert(isinstance(top_correlated_features[i], tuple))
    assert(isinstance(top_correlated_features[i][0], str))
    assert(isinstance(top_correlated_features[i][1], str))

**Task 10 (2 points).** Find top-5 most similar players to **Neymar** whose names are given. The similarity is measured as [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between vectors of players' characteristics (described in the task above). Put their names in a vector in ascending order by Euclidean distance and sorted by `player_name` if the distance is the same<br>
**Note 1:** There are many records for some players in the `Player_Attributes` table. You need to take the freshest data (characteristics with the most recent `date`). <br>
**Note 2:** Use pure values of the characteristics even if you are aware of such preprocessing technics as normalization. <br>
**Note 3:** Please avoid using any built-in methods for calculating the Euclidean distance between vectors, think about implementing your own.

In [128]:
pn= pd.read_sql("SELECT * FROM Player_Attributes", db)
player_neymar = pn.drop(['id', 'preferred_foot', 'attacking_work_rate', 'defensive_work_rate'], axis='columns', inplace=False)

In [187]:
neymar = player_data.loc[player_data.player_name == 'Neymar']
neymar_id = 19533

In [186]:
player_neymar.date = pd.to_datetime(player_neymar.date)

player_neymar = player_neymar.sort_values('date', ascending=False).drop_duplicates('player_api_id', keep='first')

In [185]:
player_neymar.fillna(0, inplace=True)

In [37]:
neymar_char = player_neymar.loc[player_neymar.player_api_id == neymar_id]

In [184]:
neymar_similarities = ['Paulo Dybala','Eden Hazard','Giovani dos Santos','Arjen Robben','Lionel Messi']# Your code here

a = neymar_char.iloc[0,3:]

from scipy.spatial import distance

def euclidean(a, b):
        return ((a - b) ** 2) ** 0.5
'''
ec = []
for i in range(0, player_neymar.shape[0]):
    ec.append(euclidean(a,player_neymar.iloc[i,3:]).sum())
'''


ec_2 = []
for i in range(0, player_neymar.shape[0]):
    ec_2.append(distance.euclidean(a, player_neymar.iloc[i,3:]))
    
    
sorted(ec_2)[:6]
#ec_2.index(43.54308211415448)
#player_neymar.iloc[5651,:]
#player_data.loc[player_data.player_api_id == 30981]

In [162]:
assert(len(neymar_similarities) == 5)
assert(isinstance(neymar_similarities, list))
for i in range(5):
    assert(isinstance(neymar_similarities[i], str))

**Task 11 (1 point).** Calculate the number of home matches played by the **Borussia Dortmund** team in **Germany 1. Bundesliga** in season **2008/2009**

In [192]:
league_data
team_data = pd.read_sql("SELECT * FROM Team", db)
team_data.loc[team_data.team_long_name == 'Borussia Dortmund']

       id  team_api_id  team_fifa_api_id     team_long_name team_short_name
97  15620         9789              22.0  Borussia Dortmund             DOR

In [207]:
borussia_bundesliga_2008_2009_matches = 17# Your code here

int(match.loc[(match.season == '2008/2009') & (match.home_team_api_id == 9789)].count()[0])

17

In [202]:
assert(isinstance(borussia_bundesliga_2008_2009_matches, int))

**Task 12 (1 point).** Find a team having the most matches (both home and away!) in the **Germany 1. Bundesliga** in **2008/2009** season. Return number of matches.

In [211]:
league_data.loc[league_data.name == 'Germany 1. Bundesliga']

     id  country_id                   name
3  7809        7809  Germany 1. Bundesliga

In [209]:
team_data

        id  team_api_id  team_fifa_api_id      team_long_name team_short_name
0        1         9987             673.0            KRC Genk             GEN
1        2         9993             675.0        Beerschot AC             BAC
2        3        10000           15005.0    SV Zulte-Waregem             ZUL
3        4         9994            2007.0    Sporting Lokeren             LOK
4        5         9984            1750.0   KSV Cercle Brugge             CEB
..     ...          ...               ...                 ...             ...
294  49479        10190             898.0       FC St. Gallen             GAL
295  49837        10191            1715.0             FC Thun             THU
296  50201         9777             324.0         Servette FC             SER
297  50204         7730            1862.0  FC Lausanne-Sports             LAU
298  51606         7896               NaN              Lugano             LUG

[299 rows x 5 columns]

In [237]:

match_data.loc[(match_data.league_id == 7809) & (match_data.season == '2008/2009')][['home_team_api_id', 'away_team_api_id']].mode().iloc[0,0]

match_data.loc[(match_data.league_id == 7809) & (match_data.season == '2008/2009') & ((match_data.home_team_api_id == 8177) | (match_data.away_team_api_id == 8177))].shape

team_most_matches_bundesliga_2008_2009 = 34# Your code here

(34, 115)

In [ ]:
assert(isinstance(team_most_matches_bundesliga_2008_2009, int))

**Task 13 (1 point).** Count total number of **Arsenal** matches (both home and away!) in the **2015/2016** season which they have won. <br><br>
**Note:** Winning a game means scoring **more** goals than an opponent.

In [240]:
team_data.loc[team_data.team_long_name == 'Arsenal']

      id  team_api_id  team_fifa_api_id team_long_name team_short_name
27  3459         9825               1.0        Arsenal             ARS

In [245]:
home_goals = int(match_data.loc[(match_data.season == '2015/2016') & (match_data.home_team_api_id == 9825) & (match_data.home_team_goal > match_data.away_team_goal)].shape[0])
away_goals = int(match_data.loc[(match_data.season == '2015/2016') & (match_data.away_team_api_id == 9825) & (match_data.home_team_goal < match_data.away_team_goal)].shape[0])

8

In [246]:
arsenal_won_matches_2015_2016 = home_goals + away_goals# Your code here

In [247]:
assert(isinstance(arsenal_won_matches_2015_2016, int))

**Task 14 (2 points).** Find a team with the highest win rate in the **2015/2016** season. Win rate means won matches / all matches. If there are several teams with the highest win rate return the first by name in lexical order

In [298]:
match_data.loc[match_data.season == '2015/2016'].home_team_api_id.unique()

win = {}
for i in match_data.loc[match_data.season == '2015/2016'].home_team_api_id.unique():
    rate = match_data.loc[(match_data.season == '2015/2016') & ((match_data.home_team_api_id == i) | (match_data.away_team_api_id == i)) & ((match_data.home_team_goal > match_data.away_team_goal) | (match_data.home_team_goal < match_data.away_team_goal))].shape[0] / match_data.loc[(match_data.season == '2015/2016') & ((match_data.home_team_api_id == i) | (match_data.away_team_api_id == i))].shape[0]
    win[i] =  rate
    #mydict['item'] = input_value
    
    
match_data.loc[match_data.season == '2015/2016'].home_team_api_id.unique()

win_a = {}
for i in match_data.loc[match_data.season == '2015/2016'].away_team_api_id.unique():
    rate_a = match_data.loc[(match_data.season == '2015/2016') & (match_data.away_team_api_id == i) & (match_data.home_team_goal < match_data.away_team_goal)].shape[0] / match_data.loc[(match_data.season == '2015/2016') & (match_data.away_team_api_id == i)].shape[0]
    win_a[i] =  rate_a
    #mydict['item'] = input_value

In [299]:
win

{9997: 0.8,
 8571: 0.7,
 9987: 0.8,
 8573: 0.7666666666666667,
 10000: 0.7666666666666667,
 10001: 0.7,
 8635: 0.6666666666666666,
 9986: 0.7,
 9991: 0.7,
 1773: 0.7333333333333333,
 8342: 0.9666666666666667,
 9985: 0.8333333333333334,
 8203: 0.7666666666666667,
 274581: 0.7,
 9994: 0.6666666666666666,
 8475: 0.8,
 9825: 0.7105263157894737,
 8678: 0.7631578947368421,
 8455: 0.631578947368421,
 8668: 0.631578947368421,
 8197: 0.6842105263157895,
 10260: 0.7631578947368421,
 10261: 0.7368421052631579,
 9850: 0.8157894736842105,
 10194: 0.7631578947368421,
 8659: 0.6578947368421053,
 10252: 0.7894736842105263,
 8650: 0.6842105263157895,
 8472: 0.6842105263157895,
 8654: 0.631578947368421,
 9826: 0.7631578947368421,
 8456: 0.7631578947368421,
 8466: 0.7631578947368421,
 10003: 0.7105263157894737,
 8586: 0.6578947368421053,
 9817: 0.7631578947368421,
 7794: 0.7894736842105263,
 9827: 0.631578947368421,
 8639: 0.6052631578947368,
 9748: 0.7894736842105263,
 8592: 0.5263157894736842,
 10249: 0.8157894736842105,
 9830: 0.6842105263157895,
 9831: 0.7631578947368421,
 9941: 0.6578947368421053,
 10242: 0.7631578947368421,
 9747: 0.7105263157894737,
 9829: 0.631578947368421,
 9837: 0.7631578947368421,
 9851: 0.6578947368421053,
 9853: 0.8157894736842105,
 8121: 0.7105263157894737,
 7819: 0.8421052631578947,
 6391: 0.6578947368421053,
 8689: 0.6578947368421053,
 9847: 0.8421052631578947,
 9823: 0.8823529411764706,
 9789: 0.8235294117647058,
 8178: 0.8235294117647058,
 8721: 0.7352941176470589,
 10269: 0.8235294117647058,
 8406: 0.6764705882352942,
 8697: 0.7647058823529411,
 9905: 0.7647058823529411,
 8262: 0.6764705882352942,
 9788: 0.8823529411764706,
 9904: 0.8823529411764706,
 8226: 0.7058823529411765,
 8234: 0.7058823529411765,
 10189: 0.7941176470588235,
 9790: 0.7647058823529411,
 9810: 0.7352941176470589,
 8722: 0.6176470588235294,
 8177: 0.7647058823529411,
 8534: 0.7368421052631579,
 8535: 0.7368421052631579,
 9891: 0.8157894736842105,
 9876: 0.6578947368421053,
 8636: 0.8157894736842105,
 9885: 0.8947368421052632,
 8543: 0.7631578947368421,
 8540: 0.7631578947368421,
 9882: 0.7368421052631579,
 7943: 0.6578947368421053,
 8524: 0.6842105263157895,
 9857: 0.7631578947368421,
 8564: 0.6842105263157895,
 9875: 0.8157894736842105,
 8686: 0.7105263157894737,
 9804: 0.7631578947368421,
 208931: 0.7105263157894737,
 8533: 0.7105263157894737,
 10233: 0.8157894736842105,
 8600: 0.7631578947368421,
 10228: 0.7352941176470589,
 6413: 0.8235294117647058,
 9803: 0.7058823529411765,
 10217: 0.6176470588235294,
 10235: 0.8235294117647058,
 10229: 0.8529411764705882,
 8464: 0.7941176470588235,
 8674: 0.7647058823529411,
 8525: 0.6764705882352942,
 8526: 0.7647058823529411,
 8611: 0.7941176470588235,
 7788: 0.7352941176470589,
 8277: 0.7058823529411765,
 9791: 0.7352941176470589,
 8593: 0.7941176470588235,
 10218: 0.7352941176470589,
 9908: 0.7647058823529411,
 8640: 0.8235294117647058,
 2182: 0.8666666666666667,
 8030: 0.7,
 8025: 0.6666666666666666,
 1601: 0.8,
 8021: 0.7,
 8245: 0.6666666666666666,
 8028: 0.7666666666666667,
 10265: 0.5666666666666667,
 8023: 0.4666666666666667,
 8019: 0.7666666666666667,
 2186: 0.7,
 8673: 0.7,
 1957: 0.8333333333333334,
 177361: 0.7,
 8020: 0.5333333333333333,
 8033: 0.6333333333333333,
 9807: 0.6764705882352942,
 9772: 0.9705882352941176,
 10264: 0.7058823529411765,
 6403: 0.7058823529411765,
 8348: 0.7352941176470589,
 10238: 0.6470588235294118,
 9773: 0.8823529411764706,
 6367: 0.7647058823529411,
 188163: 0.8235294117647058,
 158085: 0.5588235294117647,
 7844: 0.6176470588235294,
 10212: 0.8529411764705882,
 7842: 0.7647058823529411,
 10215: 0.7058823529411765,
 8613: 0.7352941176470589,
 9768: 0.8529411764705882,
 10214: 0.7647058823529411,
 7841: 0.7647058823529411,
 9925: 0.7894736842105263,
 9938: 0.8157894736842105,
 8429: 0.7368421052631579,
 9860: 0.7105263157894737,
 8066: 0.7368421052631579,
 8597: 0.7631578947368421,
 8485: 0.868421052631579,
 8284: 0.6052631578947368,
 8426: 0.7368421052631579,
 8649: 0.8421052631578947,
 9927: 0.868421052631579,
 8467: 0.7894736842105263,
 8581: 0.7894736842105263,
 9906: 0.8947368421052632,
 9864: 0.6842105263157895,
 8315: 0.7894736842105263,
 7878: 0.7631578947368421,
 8558: 0.8157894736842105,
 8603: 0.6842105263157895,
 9869: 0.7631578947368421,
 9783: 0.5263157894736842,
 8370: 0.7105263157894737,
 8372: 0.7368421052631579,
 8305: 0.7631578947368421,
 10205: 0.7368421052631579,
 8633: 0.8421052631578947,
 8560: 0.7631578947368421,
 10267: 0.7105263157894737,
 8634: 0.8947368421052632,
 8302: 0.7368421052631579,
 8306: 0.7894736842105263,
 9910: 0.7631578947368421,
 10199: 0.75,
 9931: 0.8611111111111112,
 10191: 0.6944444444444444,
 10190: 0.7777777777777778,
 10243: 0.6388888888888888,
 9956: 0.7777777777777778,
 10179: 0.7777777777777778,
 9824: 0.5833333333333334,
 10192: 0.75,
 7896: 0.7777777777777778}

In [300]:
max(win, key=win.get)

9772

In [301]:
team_data.loc[team_data.team_api_id == 9772]

        id  team_api_id  team_fifa_api_id team_long_name team_short_name
216  35294         9772             234.0     SL Benfica             BEN

In [285]:
match_data.loc[match_data.away_team_api_id == 8342]

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,4.75,3.40,1.67,4.85,3.4,1.65,3.70,3.20,1.80,5.00,3.25,1.62,NaN,NaN,NaN,4.20,3.4,1.70,5.50,3.75,1.67,4.35,3.40,1.70,4.50,3.4,1.70,NaN,NaN,NaN
20,21,1,1,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,3.20,3.30,2.25,3.25,3.2,2.10,3.10,3.00,2.10,2.75,3.25,2.20,NaN,NaN,NaN,3.00,3.2,2.10,3.30,3.30,2.10,3.25,3.25,2.00,3.10,3.2,2.15,3.10,3.25,2.10
38,39,1,1,2008/2009,13,2008-11-22 00:00:00,492622,9998,8342,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,4.33,3.40,1.85,4.85,3.4,1.65,3.80,3.10,1.80,3.75,3.30,1.80,NaN,NaN,NaN,4.20,3.4,1.75,4.75,3.50,1.73,4.50,3.40,1.70,4.60,3.4,1.73,4.20,3.40,1.73
59,60,1,1,2008/2009,15,2008-12-07 00:00:00,492696,9994,8342,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.88,3.20,2.30,3.00,3.0,2.25,2.60,3.10,2.30,2.75,3.20,2.25,NaN,NaN,NaN,2.75,3.2,2.25,3.20,3.20,2.25,2.60,3.30,2.35,2.75,3.2,2.30,2.62,3.20,2.38
78,79,1,1,2008/2009,17,2008-12-20 00:00:00,492758,9996,8342,5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,3.00,3.25,2.40,3.00,3.2,2.20,2.80,3.10,2.20,2.75,3.25,2.20,NaN,NaN,NaN,2.70,3.2,2.25,3.00,3.25,2.30,2.80,3.25,2.25,3.00,3.2,2.20,2.75,3.20,2.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670,1671,1,1,2015/2016,3,2015-08-09 00:00:00,1979854,9986,8342,0,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,5.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,41301.0,110878.0,280083.0,33605.0,46458.0,93347.0,179059.0,521204.0,240478.0,181054.0,578032.0,104384.0,543969.0,209922.0,305132.0,178293.0,201915.0,109061.0,26440.0,465730.0,203666.0,581798.0,None,None,None,None,None,None,None,None,2.90,3.25,2.40,2.75,3.4,2.40,2.75,3.30,2.40,2.90,3.40,2.38,2.99,3.50,2.44,2.75,3.3,2.38,NaN,NaN,NaN,2.88,3.40,2.40,NaN,NaN,NaN,NaN,NaN,NaN
1677,1678,1,1,2015/2016,30,2016-03-13 00:00:00,1980061,1773,8342,0,1,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,11336.0,38777.0,164229.0,179783.0,36849.0,105680.0,26078.0,181569.0,280968.0,318615.0,120110.0,34003.0,277771.0,294254.0,157375.0,178293.0,26440.0,203666.0,114688.0,315459.0,38782.0,207511.0,None,None,None,None,None,None,None,None,3.40,3.40,2.10,3.40,3.6,2.00,4.00,3.45,1.85,3.30,3.50,2.00,3.51,3.67,2.14,3.20,3.6,2.00,NaN,NaN,NaN,3.20,3.70,2.10,NaN,NaN,NaN,NaN,NaN,NaN
1691,1692,1,1,2015/2016,5,2015-08-22 00:00:00,1979867,10000,8342,2,0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,4.0,6.0,8.0,2.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,37900.0,289883.0,563215.0,46232.0,303179.0,38262.0,26916.0,604345.0,26613.0,46335.0,299358.0,104384.0,445873.0,209922.0,178293.0,41005.0,109061.0,203666.0,439368.0,113868.0,201915.0,465730.0,None,None,None,None,None,None,None,None,3.20,3.40,2.20,3.00,3.5,2.20,3.10,3.30,2.20,3.10,3.50,2.20,3.39,3.61,2.18,3.00,3.4,2.15,NaN,NaN,NaN,3.25,3.60,2.15,NaN,NaN,NaN,NaN,NaN,NaN
1708,1709,1,1,2015/2016,7,2015-09-11 00:00:00,1979876,274581,8342,2,1,1.0,2.0,4.0,6.0,8.0,7.0,3.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,128083.0,359378.0,210138.0,202471.0,118879.0,104411.0,364290.0,447455.0,387723.0,213487.0,39625.0,38797.0,277771.0,26440.0,445873.0,178293.0,109061.0,114688.0,201915.0,113868.0,203666.0,38782.0,None,None,None,None,None,None,None,None,5.75,4.20,1.53,5.75,4.2,1.53,6.10,4.00,1.50,6.00,4.20,1.53,6.83,4.50,1.52,5.50,4.2,1.50,NaN,NaN,NaN,6.50,4.40,1.50,NaN,NaN,NaN,NaN,NaN,NaN
1725,1726,1,1,2015/2016,9,2015-09-27 00:00:00,1979893,9994,8342,0,1,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,30934.0,432217.0,25791.0,149150.0,114216.0,38290.0,287341.0,67898.0,497753.0,277821.0,173922.0,104384.0,277771.0,445873.0,209922.0,178293.0,26440.0,109061.0,203666.0,465728.0,38782.0,500585.0,None,None,None,None,None,None,None,None,3.75,3.40,2.00,3.50,3.4,2.05,3.50,3.40,2.00,3.60,3.50,2.00,3.70,3.65,2.08,3.30,3.5,2.00,NaN,NaN,NaN,3.60,3.60,2.00,NaN,NaN,NaN,NaN,NaN,NaN

In [293]:
max(win_a, key=win_a.get)

9768

In [297]:
match_data.loc[(match_data.season == '2015/2016') & ((match_data.home_team_api_id == 8342) | (match_data.away_team_api_id == 8342)) & ((match_data.home_team_goal > match_data.away_team_goal) | (match_data.home_team_goal < match_data.away_team_goal))].shape[0] / match_data.loc[(match_data.season == '2015/2016') & ((match_data.home_team_api_id == 8342) | (match_data.away_team_api_id == 8342))].shape[0]

0.9666666666666667

In [302]:
team_highest_winrate_2015_2016 = 'SL Benfica'# Your code here

In [292]:

assert(isinstance(team_highest_winrate_2015_2016, str))

**Task 15 (2 points).** Determine the team with the maximum days' gap between matches in **England Premier League 2010/2011 season**. Return number of days in that gap. <br>
**Note**: a *gap* means the number of days between two consecutive matches of the same team.

In [405]:
match_data.groupby(by=['home_team_api_id', 'away_team_api_id'], as_index=False)

In [399]:
match_data.loc[(match_data.league_id == 1729) & (match_data.season == '2010/2011')].sort_values(by=['date', 'home_team_api_id', 'away_team_api_id'])

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
2491,2492,1729,1729,2010/2011,1,2010-08-14,839800,8455,8659,6,0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,5.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,30859.0,30856.0,26564.0,30627.0,38834.0,30631.0,32345.0,30675.0,37804.0,30822.0,30679.0,36373.0,49885.0,37428.0,30903.0,25922.0,24171.0,71502.0,23257.0,23954.0,32734.0,32570.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>56</comment><event...,1.17,7.0,17.00,1.15,6.75,16.00,1.15,6.2,14.0,1.14,7.50,19.00,NaN,NaN,NaN,1.17,6.50,19.00,1.18,6.5,15.00,1.17,7.50,19.00,1.16,6.75,16.00,1.17,6.50,15.00
2494,2495,1729,1729,2010/2011,1,2010-08-14,839803,8472,8658,2,2,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,37868.0,24209.0,24230.0,30885.0,30352.0,111930.0,25150.0,156008.0,38802.0,24157.0,23949.0,24147.0,24226.0,23837.0,34193.0,23787.0,35443.0,33049.0,24978.0,77704.0,31953.0,26559.0,<goal><value><comment>p</comment><stats><penal...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>53</comment><event...,2.10,3.3,3.60,2.15,3.20,3.30,2.10,3.2,3.2,2.10,3.30,3.50,NaN,NaN,NaN,2.15,3.20,3.50,2.20,3.4,3.20,2.20,3.25,3.50,2.15,3.25,3.30,2.10,3.25,3.40
2497,2498,1729,1729,2010/2011,1,2010-08-14,840184,8528,8483,0,4,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,34421.0,35472.0,11736.0,25948.0,111865.0,101192.0,40015.0,106228.0,22991.0,71550.0,18859.0,24694.0,24469.0,35554.0,40548.0,23065.0,39109.0,40563.0,46344.0,23464.0,24772.0,23299.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><corners>1</corners></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>60</comment><event...,1.83,3.5,4.50,1.78,3.40,4.50,1.90,3.3,3.7,1.80,3.50,4.50,NaN,NaN,NaN,1.75,3.40,5.00,1.83,3.5,4.33,1.83,3.40,4.75,1.80,3.40,4.33,1.80,3.40,4.50
2490,2491,1729,1729,2010/2011,1,2010-08-14,839799,8559,9879,0,0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,8.0,6.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,5.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,23932.0,26454.0,23783.0,40128.0,24728.0,130670.0,35532.0,33633.0,24455.0,34261.0,23934.0,35477.0,37266.0,23780.0,26777.0,33045.0,24020.0,25253.0,30338.0,34574.0,24737.0,24741.0,<goal />,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>50</comment><event...,2.20,3.3,3.40,2.15,3.25,3.25,2.20,3.2,3.0,2.25,3.30,3.20,NaN,NaN,NaN,2.15,3.20,3.50,2.30,3.4,3.00,2.20,3.30,3.40,2.20,3.25,3.20,2.20,3.20,3.25
2495,2496,1729,1729,2010/2011,1,2010-08-14,839804,8586,8456,0,0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,30455.0,46403.0,24531.0,30354.0,40006.0,30895.0,24656.0,31097.0,31921.0,30830.0,30348.0,31432.0,24208.0,30831.0,39027.0,16351.0,30367.0,36615.0,30598.0,23782.0,37459.0,38817.0,<goal />,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>70</comment><event...,2.40,3.3,3.00,2.35,3.30,2.85,2.40,3.2,2.7,2.30,3.30,3.00,NaN,NaN,NaN,2.38,3.25,3.00,2.38,3.4,2.88,2.30,3.40,3.10,2.35,3.30,2.85,2.38,3.30,2.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2805,2806,1729,1729,2010/2011,38,2011-05-22,840232,9879,9825,2,2,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,30633.0,23780.0,30890.0,26777.0,78511.0,30956.0,30338.0,23283.0,24664.0,24741.0,31907.0,169718.0,26111.0,30986.0,26005.0,78513.0,27277.0,143793.0,26181.0,75489.0,30843.0,25537.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>41</comment><event...,3.75,3.6,1.95,3.80,3.40,1.90,3.30,3.3,2.0,3.60,3.50,2.00,NaN,NaN,NaN,3.50,3.40,1.95,3.50,3.5,1.95,3.75,3.75,2.00,3.75,3.50,1.90,3.50,3.25,2.00
2807,2808,1729,1729,2010/2011,38,2011-05-22,840234,10194,8528,0,1,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,46518.0,23369.0,40695.0,24408.0,47418.0,34601.0,23253.0,25668.0,24773.0,33881.0,30988.0,25156.0,35472.0,41071.0,11736.0,111865.0,40015.0,101192.0,29581.0,22991.0,77727.0,71550.0,<goal><value><comment>dg</comment><event_incid...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><event_incident_typefk>123</even...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>57</comment><event...,2.75,3.6,2.40,2.75,3.50,2.30,2.80,3.2,2.3,2.88,3.40,2.38,NaN,NaN,NaN,2.70,3.20,2.30,2.75,3.3,2.40,2.75,3.60,2.50,2.75,3.30,2.40,2.62,3.50,2.38
2801,2802,1729,1729,2010/2011,38,2011-05-22,840228,10252,8650,1,0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,30380.0,159833.0,24751.0,24211.0,30357.0,38609.0,24780.0,78324.0,23354.0,23949.0,30892.0,30660.0,239856.0,30617.0,22764.0,34222.0,25923.0,95331.0,95327.0,30630.0,37139.0,40636.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><corners>1</corners></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>33</comment><event...,3.20,3.4,2.25,3.15,3.35,2.15,2.80,3.2,2.3,3.00,3.25,2.38,NaN,NaN,NaN,2.62,3.20,2.30,3.00,3.3,2.25,3.25,3.40,2.30,3.00,3.30,2.25,3.00,3.25,2.25
2798,2799,1729,1729,2010/2011,38,2011-05-22,840225,10260,8483,4,2,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,30726.0,38994.0,30865.0,43248.0,32569.0,40961.0,30373.0,24148.0,40945.0,27430.0,30802.0,24694.0,29571.0,35554.0,24469.0,23065.0,23736.0,39109.0,40563.0,23464.0,21853.0,35345.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>60</comment><event...,1.60,4.0,5.50,1.55,4.10,5.25,1.65,3.8,4.0,1.53,4.33,5.50,NaN,NaN,NaN,1.57,3.80,5.00,1.50,4.2,5.50,1.62,4.20,5.50,1.60,4.00,5.00,1.62,4.00,4.50
2803,2804,1729,1729,2010/2011,38,2011-05-22,840230,10261,8659,3,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,5.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,24229.0,49571.0,30929.0,24228.0,37475.0,24890.0,24205.0,40565.0,174326.0,36412.0,24225.0,36373.0,23922.0,37280.0,26527.0,23282.0,23257.0,71502.0,25005.0,33790.0,24171.0,26494.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card />,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>52</comment><event...,2.00,3.5,3.75,1.95,3.45,3.60,1.90,3.3,3.7,2.00,3.50,3.60,NaN,NaN,NaN,1.91,3.30,3.30,2.00,3.5,3.40,2.05,3.50,3.75,2.00,3.30,3.60,2.00,3.25,3.50

In [456]:

league_data.loc[league_data.name == 'England Premier League']
home_teams = match_data.loc[(match_data.league_id == 1729) & (match_data.season == '2010/2011')].home_team_api_id.unique()
home_teams[0]
match_data.date = pd.to_datetime(match_data.date)

In [457]:
new = pd.merge(match_data.loc[(match_data.league_id == 1729)
                              & (match_data.season == '2010/2011')][['date', 'home_team_api_id']], match_data.loc[(match_data.league_id == 1729) 
                                & (match_data.season == '2010/2011')][['date', 'away_team_api_id']])

In [462]:
new = new.sort_values(by=['date','home_team_api_id', 'away_team_api_id'])

In [486]:
sorted(new.home_team_api_id.unique())

[8455,
 8456,
 8472,
 8483,
 8528,
 8559,
 8586,
 8602,
 8650,
 8654,
 8655,
 8658,
 8659,
 8668,
 9825,
 9879,
 10194,
 10252,
 10260,
 10261]

In [489]:
sorted(new.away_team_api_id.unique())

[8455,
 8456,
 8472,
 8483,
 8528,
 8559,
 8586,
 8602,
 8650,
 8654,
 8655,
 8658,
 8659,
 8668,
 9825,
 9879,
 10194,
 10252,
 10260,
 10261]

In [466]:
new.date.diff().max().days

13

In [479]:
new.loc[(new.home_team_api_id == 8455)].date.diff().max()

Timedelta('25 days 00:00:00')

In [494]:
for i in sorted(new.home_team_api_id.unique()):
    max_delta_for_team = new.loc[(new.home_team_api_id == i) | (new.away_team_api_id == i)].date.diff().max().days
    print(max_delta_for_team)

15
15
16
17
15
15
14
14
18
15
16
18
15
15
14
15
16
15
16
15

In [ ]:
 for i in sorted(new.home_team_api_id.unique()):
    max_delta_for_team = new.loc[(new.home_team_api_id == i)].date.diff().max().days
    print(i, max_delta_for_team)

In [467]:
#match_data.loc[(match_data.league_id == 1729) & (match_data.season == '2010/2011') & ((match_data.home_team_api_id == home_teams[0]) | (match_data.away_team_api_id == home_teams[0]))].sort_values(by=['date'])

In [391]:
max_days = []
for i,j in enumerate(home_teams):
    max_delta_for_team = match_data.loc[(match_data.league_id == 1729) & (match_data.season == '2010/2011') & (match_data.home_team_api_id == home_teams[i])].sort_values(by=['date'])
    max_days.append(max_delta_for_team.sort_values(by=['home_team_api_id']).date.diff().max().days)

In [394]:
max(max_days)

254

In [495]:
highest_gap_england_2010_2011 = 18
# Your code here

In [304]:
assert(isinstance(highest_gap_england_2010_2011, int))

### Warning! Do not change anything in the area below

In [391]:
with open('student_answers.txt', 'w') as file:
    file.write(f"{players_180_190}\n")
    file.write(f"{players_1980}\n")
    file.write(f"{highest_players}\n")
    file.write(f"{years_born_players}\n")
    file.write(f"{round(adriano_mean, 3)} {round(adriano_std, 3)}\n")
    file.write(f"{dow_with_min_players_born}\n")
    file.write(f"{league_most_matches}\n")
    file.write(f"{max_matches_player}\n")
    file.write(f"{';'.join(['%s,%s' % tup for tup in top_correlated_features])};\n")
    file.write(f"{neymar_similarities}\n")
    file.write(f"{borussia_bundesliga_2008_2009_matches}\n")
    file.write(f"{team_most_matches_bundesliga_2008_2009}\n")
    file.write(f"{arsenal_won_matches_2015_2016}\n")
    file.write(f"{team_highest_winrate_2015_2016}\n")
    file.write(f"{highest_gap_england_2010_2011}\n")